### ISSUE TITLE
Split long messages into multiple tweets

### ISSUE THREAD

**Issue by AetherUnbound** [SeattleDSA/signal-scanner-bot#2]
### Description

If a messages is too long to tweet, currently it's just discarded. This should be split into multiple messages and tweeted as a thread. Hashtags will need to be considered as part of the length.

**Comment by mpuckett159** [comment]
Code committed to my fork but still need to test more fully. Currently have just run through flake8 and setup.py test. Need to test feeding in some actual example data and dump out to the Twitter API before merging into the main repo. Will reconvene with AetherUnbound at some point to do fuller testing.

**Comment by AetherUnbound** [comment]
Thank you @mpuckett159! I'm currently working on a testing suite now for the entire codebase, and I'm hoping to have some testing tools down the line for mocking out the Twitter API interactions. If you believe you have a functional set of code, (I can't believe I'm saying this but) let's try to see if we can get it working/merged in - thorough tests can (and will) come later. I'll also add you to the project so you can make a branch directly on this repo.
