### ISSUE TITLE
Add calculation function for tweet padding to remove static values

### ISSUE THREAD

**Issue by mpuckett159** [SeattleDSA/signal-scanner-bot#28]
### Description

Add a function to calculate the amount of padding necessary to more modularly and accurately calculate the the tweet lengths required. This would remove the reliance on the static tweet padding setting.

**Comment by mpuckett159** [comment]
There's no point in doing this. It would be needlessly complicated, and we should never be sending more than 99 tweets in a single thread, so we will just be adding a check capping the tweet list length off at len == 99 instead.

**Comment by AetherUnbound** [comment]
> we should never be sending more than 99 tweets in a single thread

You _say_ that now... :wink:

**Comment by mpuckett159** [comment]
This is true. I guess I'll just add an environment variable for this actually, and a quick calculation based on the number of digits for the max tweet thread length. That way we don't have to do any wonky re-calculating and shifting words around between tweets after we get a list we can check the length against. Still a little cludgy but we're only loosing a couple characters this way instead of like 10-15.
