### ISSUE TITLE
Add hashtag configuration to .env file

### ISSUE THREAD

**Issue by mpuckett159** [SeattleDSA/signal-scanner-bot#33]
### Description

Add an input in the .env file so that users can modularly add hashtags to send and receive from. This will simplify getting the bot up and running for users and allow them to pick and chose what hashtags they want included in their deployment.

e.g.
SEND_HASHTAGS="_sendhashtag1,_sendhashtag2,_sendhashtag3"
RECEIVE_HASHTAGS = "_receivehashtag1"

**Comment by AetherUnbound** [comment]
While we're at it, the message prefixes should also be an `.env` file value rather than hard-coded!
