### ISSUE TITLE
Rationalize function locations in modules

### ISSUE THREAD

**Issue by mpuckett159** [SeattleDSA/signal-scanner-bot#41]
### Description

While we were looking at the empty retweet bug we came to the conclusion that the functions weren't super organized and that we might want to rethink how they're organizing these functions. This is a pretty open ended issue. I have nothing in particular to contribute at this time.

**Comment by mpuckett159** [comment]
I kind of want to kill off the messages module and part all those functions out to their associated twitter/signal modules. Is that crazy?

**Comment by AetherUnbound** [comment]
If you think there's a good replacement for it, I could see it! But the impetus for it (that I recall) was that there were methods that used both twitter and signal components, but I didn't want all that logic shoved into the transport module. If you think there's a way around that or a better way to structure it, I'm game!

**Comment by mpuckett159** [comment]
Ok that makes sense, I'll read through it a bit and see if I still feel that way with this in mind.

**Comment by mpuckett159** [comment]
Ok after doing an quick review I think we could do this and it wouldn't be crazy or a huge lift or anything. Proposing that we move functions to files as follows:

filters.py:
- `D` TypeVar
- `_pass_filters `- also probably rename to just `pass_filters` since we will be using it in the twitter and signal modules after this move.

signal.py:
- `NON_ALPHA_NUMERIC` constant
- `_is_scanner_message`
- `_condense_command`
- `process_signal_message`

twitter.py:
- `_strip_tweet_hashtags`
- `get_tweet_text`
- `build_tweet_url`
- `format_tweet_text`
- `format_retweet_text`
- `process_twitter_message`

Note there are a few new functions especially in the twitter related stuff. I did a bit of a revamp on how I was doing some of that logic so that it would hopefully be easier to update (and understand) down the line especially for the eventual queuing updates. I'm pushing the changes now so you can take a look at them. They aren't substantially changing anything, it's mostly cosmetic stuff, but I think it'll be a net gain for code readability/maintainability.

**Comment by AetherUnbound** [comment]
We discussed this a bit already but just making a not here - I think we should try and pull out the functions that are specific to twitter/signal into the respective modules as best we can, and only have `messages.py` for functions that require *both* `signal.py` and `twitter.py` functions

**Comment by mpuckett159** [comment]
Ok, so, I've been reviewing this and the changes I've made, and the three functions that we have that are leading to circular imports are the `send_tweet` , the `send_message` (signal), and `panic` (also signal) functions.

So that gets into how we're looking to handle messages with a queue, so I think for the time being you're correct it make sense to maintain the `messages.py` module that is specifically for (for now) sending the messages to each API, and then when we do the queue update we can break it out better so that we have a queue (or just have it be part of the twitter/signal modules) and that will decouple the two modules nice and cleanly so that the twitter and signal modules are only sending stuff to the queues, then we have something else that is pulling stuff out of the queues and actually sending the messages out to Twitter and Signal.

Hopefully that made sense.

**Comment by AetherUnbound** [comment]
Sounds good to me! I hadn't considered adding queues for both streams, but that might make sense too - we can maybe look into adjusting the timeout for the signal listening loop to possibly allow more opportunities for messages to be sent. Something to think about!
