### ISSUE TITLE
Add "drink water" message

### ISSUE THREAD

**Issue by AetherUnbound** [SeattleDSA/signal-scanner-bot#53]
A comrade has asked that we add a process for the bot which sends out a daily reminder around 2pm PST to drink water. This is a lovely suggestion and certainly feasible - for us this will necessitate a new `_CONTACT` environment variable, since our general channel is different from the scanner one.

**Comment by JacksonMaxfield** [comment]
I have this as a "posture and water check" reminder on slack every day :)

**Comment by AetherUnbound** [comment]
> I have this as a "posture and water check" reminder on slack every day :)

I have to say it's not a reminder I need because I drink water like crazy during the day but it seemed like a useful suggestion!
