### ISSUE TITLE
Automatically detect timezone

### ISSUE THREAD

**Issue by AetherUnbound** [SeattleDSA/signal-scanner-bot#8]
We want message timestamps to be in PDT, but the server this runs on is in UTC. For time checks, we'll need to make sure that the time being compared is in the right timezone, while the time posted is in PDT.

**Comment by mpuckett159** [comment]
I'm gonna add a field to the .env field to allow administrators to set their own timezone to enable people in other timezones.

**Comment by AetherUnbound** [comment]
Great idea!
