### ISSUE TITLE
Fix the CRLF to LF issue

### ISSUE THREAD

**Issue by mpuckett159** [SeattleDSA/signal-scanner-bot#84]
When people are developing on Windows the CRLF problem rears its head. I don't know if the solution to this is to use dos2unix or if there's a slightly less cludgy solution.

**Comment by mpuckett159** [comment]
Opposite, Unix/Linux systems don't like the carriage return + line feed newline delineation, and Windows defaults to that, so when you build a container from a Windows system and haven't made sure that your sh files (specifically the register-number.sh file here) only have LFs in them you can spend a bunch of time trying to troubleshoot the problem because the associated error messages are extremely vague. Adding a step in the Dockerfile to run dos2unix on all the files in the directory will (most likely) fix this, but I wanted to investigate a little further and see if there was any way we could solve this a little better.

**Comment by AetherUnbound** [comment]
Ahhh, got it. Yea I think if anything that should be a pre-commit check, not something that's included in the Dockerfile.

**Comment by mpuckett159** [comment]
Well the thing is, it doesn't really matter if the files are pushed to GitHub with or without CRLF. There's a git config setting you can pass (`core.autocrlf` set to `true`) but rather than assume our user has this git setting set properly I think it would be best to have a conversion in the Dockerfile itself just to be safe and save others who may not be that familiar with the CRLF vs LF issue a bunch of time.

**Comment by AetherUnbound** [comment]
What I mean by the pre-commit check (or even a PR check!) is that this should be addressed at development time, not compile time. Also if someone tries to run the code directly on unix (outside of docker) they'll encounter the same problem. I agree that we shouldn't expect everyone who contributes to have that set, but I'd rather have this as a PR check or something similar than a step in the Dockerfile.

**Comment by mpuckett159** [comment]
I'm not talking about it from a contribution perspective but from the perspective of someone cloning down the repo then trying to run it.

**Comment by AetherUnbound** [comment]
Okay my understanding is that LF works on both unix (and thus docker) and windows, but CRLF only works on windows. So my suggestion is that we enforce LF for all files in this repo, that way we don't need to worry about fixing it when building the docker image and any user can clone/run the repo on any machine. I may be incorrect about my premise though.

**Comment by mpuckett159** [comment]
So the issue is that if someone on Windows clones the repo and does nothing else (and doesn't have that non-default setting set) it will clone the files down in the Windows format (with the CRLF in them) regardless of whether they exist in the files in the git repo hosted on GitHub or not. That means that if they build the container image locally from the source files that have not been edited by them, the container will fail to run the `register-number.sh` file due to the CRLF issue.

**Comment by AetherUnbound** [comment]
Oh man, that is exceptionally annoying

**Comment by mpuckett159** [comment]
Yeah. I thought I remembered being able to set this setting in the repo itself so that it wasn't reliant on end users having the setting set properly but I can't find it anywhere so I think we're gonna have to go the dos2unix route unfortunately, which is kind of annoying.

**Comment by AetherUnbound** [comment]
_shakes fist at sky_ Windows

**Comment by mpuckett159** [comment]
![image](https://user-images.githubusercontent.com/13648427/143954486-427510f5-306b-4511-98c9-6cbae3a6ab51.png)

**Comment by mpuckett159** [comment]
This actually fixed at some point by me and I guess I forgot about the issue.

**Comment by AetherUnbound** [comment]
Oh nice lol
